# Visão geral e roteiro do curso

Em nossas práticas, utilizaremos dados moleculares na condução das análises filogenéticas. Quanto aos métodos de inferência filogenética, rodaremos análises de máxima verossimilhança e bayesiana. Não rodaremos análises de parsimônia, uma vez que o enfoque do curso será nos dados moleculares. Atualmente, é consensual que ambas as análises, de máxima verossimilhança e bayesiana, são mais apropriadas do que a máxima parsimônia quando se tratam de dados moleculares (genotípicos). Não obstante, a análise de parsimônia continua a ser uma abordagem importante quando os dados são de natureza fenotípica (por exemplo, morfológicos).

Iniciaremos nossas atividades com a etapa de montagem de sequências, onde aprenderemos a montar uma sequência consenso a partir dos *primers* sequenciados.

Em seguida, aprenderemos a baixar sequências do *Genbank* e a editar os principais tipos de arquivos que armazenam dados filogenéticos. Para isso, faremos uso das expressões regulares através de um editor de texto plano.

Então, realizaremos o alinhamento múltiplo e manual das sequências, onde construiremos a matriz com os dados moleculares.

Aprenderemos o básico sobre o terminal (ou console ou *shell*) do Windows - `MS-DOS`, conhecimentos que serão essenciais utilizar aplicativos com interface de linha de comando (CLI, em inglês) e para procederemos as análises filogenéticas.

As análises filogenéticas serão rodadas com dados moleculares. Utilizaremos os programas `IQ-TREE` para máxima verossimilhança, e `MrBayes` e `Beast2` para bayesiana.

Então, aprenderemos o básico sobre o `r fa("r-project", fill = "steelblue")` para apresentarmos os principais pacotes desenvolvidos para análises filogenéticas e afins. Uma grande atenção será dada à edição de árvores filogenéticas através de três pacotes (`ape`, `phytools`, `ggtree`).

Finalmente, uma introdução ao `RMarkdown` para redação da documentação e apresentação dos códigos encerra o curso de introdução à filoinformática.